(()=>{
const API={exchange:'/api/partner/sso-exchange',me:'/api/partner/me',dashboard:'/api/partner/dashboard',referrals:'/api/partner/referrals',earnings:'/api/partner/earnings',settlements:'/api/partner/settlements',payout:'/api/partner/payout-profile',request:'/api/partner/settlements/request',policies:'/api/partner/policies'};
const POLICY_VERSION='2026.08.07';
const META={all:{api:'ALL',label:'전체 합계',short:'전체',title:'전체 정산 합계',banner:'콜태그 × 페이지로 전체 수익',copy:'두 서비스의 추천 수익을 합산해 표시합니다.',code:'통합 추천인 코드'},calltag:{api:'CALLTAG',label:'콜태그',short:'콜태그',title:'콜태그 정산',banner:'콜태그 추천 수익',copy:'콜태그 유료 구독에서 발생한 추천 수익만 표시합니다.',code:'콜태그 추천인 코드'},pagero:{api:'PAGERO',label:'페이지로',short:'페이지로',title:'페이지로 정산',banner:'페이지로 추천 수익',copy:'페이지로 유료 구독에서 발생한 추천 수익만 표시합니다.',code:'페이지로 추천인 코드'}};
const state={authenticated:false,scope:'all',code:'',inviteUrl:'',dashboard:null,canRequestSettlement:false,cache:{dashboard:new Map(),referrals:new Map(),earnings:new Map(),settlements:new Map()},loaded:new Set()};
const $=id=>document.getElementById(id);const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(Number(v)):'—';const number=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('ko-KR').format(Number(v)):'—';const date=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'short',day:'numeric'}).format(d)};const toast=m=>{const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)};const alert=m=>{const e=$('alertBox');e.textContent=m;e.classList.toggle('show',!!m)};
const statusMap={ESTIMATED:['예상',''],PENDING_CONFIRMATION:['확정 대기','warn'],CONFIRMED:['정산 가능','good'],REQUESTED:['지급 요청','warn'],PROCESSING:['처리 중','warn'],PAID:['지급 완료','good'],HELD:['보류','danger'],REVERSED:['차감','danger'],ACTIVE:['구독 중','good'],TRIAL:['무료체험','warn'],CANCELED:['해지',''],EXPIRED:['만료','danger']};const status=v=>{const i=statusMap[v]||[v||'확인 중',''];return `<span class="status ${i[1]}">${safe(i[0])}</span>`};
async function req(url,opt={}){const r=await fetch(url,{credentials:'include',headers:{accept:'application/json',...(opt.body?{'content-type':'application/json'}:{})},...opt});if(r.status===401){const e=new Error('AUTH');e.code=401;throw e}if(!r.ok){const e=new Error('HTTP');e.code=r.status;throw e}return r.status===204?null:r.json()}
const withScope=(url,scope=state.scope)=>scope==='all'?url:`${url}${url.includes('?')?'&':'?'}service=${META[scope].api}`;
const empty=(id,cols,msg)=>$(id).innerHTML=`<tr><td class="empty-cell" colspan="${cols}">${safe(msg)}</td></tr>`;function setConn(on,label){const e=$('serviceStatus');e.classList.toggle('online',on);e.querySelector('span').textContent=label}function setShare(on){['copyCodeBtn','copyLinkBtn','shareBtn'].forEach(id=>$(id).disabled=!on)}
function savedConsent(){try{return JSON.parse(localStorage.getItem('calltagPartnerPolicyConsent')||'null')?.version===POLICY_VERSION}catch{return false}}
function rememberConsent(action){try{localStorage.setItem('calltagPartnerPolicyConsent',JSON.stringify({version:POLICY_VERSION,acceptedAt:new Date().toISOString(),action}))}catch{}}
async function persistConsent(action){rememberConsent(action);try{await req(API.policies,{method:'POST',body:JSON.stringify({version:POLICY_VERSION,action,service:META[state.scope].api,acceptedAt:new Date().toISOString()})})}catch(e){if(![404,405].includes(e.code))console.warn('policy consent persistence failed',e)}}
function serviceCode(x){const raw=String(x?.service||x?.serviceCode||x?.productService||x?.sourceService||x?.productCode||x?.productName||'').toUpperCase();if(raw.includes('PAGERO')||raw.includes('페이지로'))return'pagero';if(raw.includes('CALLTAG')||raw.includes('콜태그'))return'calltag';return''}
function serviceLabel(x){const code=serviceCode(x);return code?META[code].label:(state.scope==='all'?'미분류':META[state.scope].label)}
function scopeItems(items,scope=state.scope){if(!Array.isArray(items))return[];if(scope==='all')return items;return items.filter(x=>{const code=serviceCode(x);return code?code===scope:scope==='calltag'})}
function extractItems(d){return d?.items||d?.data?.items||(Array.isArray(d)?d:[])}
function pickServiceDashboard(raw,scope){if(scope==='all')return raw?.totals||raw?.total||raw;const key=META[scope].api;const explicit=raw?.services?.[key]||raw?.services?.[scope]||raw?.byService?.[key]||raw?.byService?.[scope]||raw?.[scope];if(explicit)return explicit;const code=serviceCode(raw);if(code)return code===scope?raw:{};return scope==='calltag'?raw:{}}
function metric(d,...keys){for(const k of keys){const v=d?.[k];if(v!==undefined&&v!==null)return v}return null}
function syncRequestButton(){const consent=$('settlementConsent');$('requestBtn').disabled=!(state.canRequestSettlement&&consent?.checked)}
function renderTotals(raw){const d=pickServiceDashboard(raw,'all')||{};$('totalReferrals').textContent=number(metric(d,'referralCount','totalReferralCount'));$('totalEstimated').textContent=money(metric(d,'estimatedEarnings','totalEstimatedEarnings'));$('totalAvailable').textContent=money(metric(d,'availableAmount','totalAvailableAmount'));$('totalPaid').textContent=money(metric(d,'totalPaidAmount','paidAmountTotal'))}
function earnings(items,id,compact){const a=scopeItems(items);const cols=compact?8:9;if(!a.length)return empty(id,cols,`${META[state.scope].label} 수익 내역이 없습니다.`);$(id).innerHTML=a.map(x=>`<tr><td data-label="발생일">${safe(date(x.occurredAt||x.createdAt))}</td><td data-label="서비스">${safe(serviceLabel(x))}</td><td data-label="추천 회원">${safe(x.memberNameMasked||x.referralLabel||'—')}</td><td data-label="상품">${safe(x.productName||'—')}</td>${compact?'':`<td data-label="결제금액">${safe(money(x.paymentAmount))}</td>`}<td data-label="인정 매출">${safe(money(x.recognizedRevenue))}</td><td data-label="수익률">${safe(x.partnerRate!=null?x.partnerRate+'%':'—')}</td><td data-label="파트너 수익"><strong>${safe(money(x.partnerEarning))}</strong></td><td data-label="상태">${status(x.status)}</td></tr>`).join('')}
function renderDashboard(raw){const d=pickServiceDashboard(raw,state.scope)||{};state.dashboard=d;state.code=d?.referralCode||d?.referral?.code||raw?.referralCode||raw?.referral?.code||'';state.inviteUrl=d?.inviteUrl||d?.referral?.inviteUrl||raw?.inviteUrl||raw?.referral?.inviteUrl||'';state.canRequestSettlement=!!metric(d,'canRequestSettlement');$('referralCode').textContent=state.code||'코드 없음';setShare(!!state.code);$('metricReferrals').textContent=number(metric(d,'referralCount','totalReferralCount'));$('metricPaid').textContent=number(metric(d,'paidReferralCount','totalPaidReferralCount'));$('metricEstimated').textContent=money(metric(d,'estimatedEarnings','totalEstimatedEarnings'));$('metricConfirmed').textContent=money(metric(d,'availableAmount','totalAvailableAmount'));$('metricPaidTotal').textContent=money(metric(d,'totalPaidAmount','paidAmountTotal'));$('metricNextDate').textContent=date(metric(d,'nextSettlementAt'));$('metricNextNote').textContent=d?.nextSettlementLabel||'매월 15일 지급';$('requestAmount').textContent=money(metric(d,'availableAmount','totalAvailableAmount'));$('requestHelp').textContent=d?.requestDisabledReason||'10,000원 이상부터 신청할 수 있습니다.';syncRequestButton();earnings(d?.recentEarnings||raw?.recentEarnings||[],'recentEarningsBody',true)}
function renderScopeText(){const m=META[state.scope];$('pageTitle').textContent=m.title;$('serviceBadge').textContent=m.short;$('serviceBannerTitle').textContent=m.banner;$('serviceBannerCopy').textContent=m.copy;$('referralLabel').textContent=m.code;$('quickService').textContent=m.label;$('recentEarningsTitle').textContent=`${m.label} 최근 수익`;$('referralsTitle').textContent=`${m.label} 추천 회원`;$('earningsTitle').textContent=`${m.label} 수익 내역`;$('settlementsTitle').textContent=`${m.label} 정산 내역`;$('requestService').textContent=m.short;$('standardsTitle').textContent=`${m.label} 수익·정산 기준`;document.querySelectorAll('.service-tab').forEach(b=>{const on=b.dataset.service===state.scope;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))})}
function business(){const on=$('payoutType').value!=='INDIVIDUAL';$('businessFields').hidden=!on;$('businessNumberField').hidden=!on;$('taxEmailField').hidden=!on}
async function dashboardFor(scope,force=false){if(!force&&state.cache.dashboard.has(scope))return state.cache.dashboard.get(scope);const d=await req(withScope(API.dashboard,scope));state.cache.dashboard.set(scope,d);return d}
async function initial(force=false){alert('');$('syncBtn').disabled=true;setConn(false,'연결 확인 중');try{const p=new URLSearchParams(location.search),ticket=p.get('ticket');if(ticket){await req(API.exchange,{method:'POST',body:JSON.stringify({ticket})});p.delete('ticket');history.replaceState({},'',location.pathname+(p.toString()?'?'+p:''))}const [me,total,current]=await Promise.all([req(API.me),dashboardFor('all',force),state.scope==='all'?Promise.resolve(null):dashboardFor(state.scope,force)]);state.authenticated=true;renderTotals(total);renderDashboard(current||total);setConn(true,me?.displayName?me.displayName+' 로그인':'로그인됨');state.loaded.add(`${state.scope}:overview`)}catch(e){state.authenticated=false;state.canRequestSettlement=false;syncRequestButton();setConn(false,'연결 필요');setShare(false);$('referralCode').textContent='로그인 필요';['metricReferrals','metricPaid','metricEstimated','metricConfirmed','metricPaidTotal','metricNextDate','totalReferrals','totalEstimated','totalAvailable','totalPaid'].forEach(id=>$(id).textContent='—');empty('recentEarningsBody',8,'로그인 후 수익 내역이 표시됩니다.');alert(e.code===401?'콜태그 앱 또는 페이지로 계정에서 정산 메뉴를 열어 주세요.':'정산 서버 연결을 준비 중입니다.')}finally{$('syncBtn').disabled=false}}
async function load(name,force=false){if(name==='standards'||!state.authenticated)return;const key=`${state.scope}:${name}`;if(!force&&state.loaded.has(key))return;try{if(name==='referrals'){let d=force||!state.cache.referrals.has(state.scope)?await req(withScope(API.referrals)):state.cache.referrals.get(state.scope);state.cache.referrals.set(state.scope,d);const a=scopeItems(extractItems(d));if(!a.length)empty('referralsBody',8,`${META[state.scope].label} 추천 회원이 없습니다.`);else $('referralsBody').innerHTML=a.map(x=>`<tr><td data-label="서비스">${safe(serviceLabel(x))}</td><td data-label="회원">${safe(x.nameMasked||'—')}</td><td data-label="이메일">${safe(x.emailMasked||'—')}</td><td data-label="가입일">${safe(date(x.joinedAt))}</td><td data-label="무료체험">${status(x.trialStatus)}</td><td data-label="첫 결제일">${safe(date(x.firstPaidAt))}</td><td data-label="구독 상태">${status(x.subscriptionStatus)}</td><td data-label="이번 달 인정액">${safe(money(x.recognizedAmountThisMonth))}</td></tr>`).join('')}
if(name==='earnings'){let d=force||!state.cache.earnings.has(state.scope)?await req(withScope(API.earnings)):state.cache.earnings.get(state.scope);state.cache.earnings.set(state.scope,d);earnings(extractItems(d),'earningsBody',false)}
if(name==='settlements'){let d=force||!state.cache.settlements.has(state.scope)?await req(withScope(API.settlements)):state.cache.settlements.get(state.scope);state.cache.settlements.set(state.scope,d);const a=scopeItems(extractItems(d));if(!a.length)empty('settlementsBody',7,`${META[state.scope].label} 정산 내역이 없습니다.`);else $('settlementsBody').innerHTML=a.map(x=>`<tr><td data-label="정산번호">${safe(x.settlementNumber||x.id||'—')}</td><td data-label="서비스">${safe(serviceLabel(x))}</td><td data-label="대상 기간">${safe(x.periodLabel||'—')}</td><td data-label="신청일">${safe(date(x.requestedAt))}</td><td data-label="금액"><strong>${safe(money(x.amount))}</strong></td><td data-label="지급일">${safe(date(x.paidAt))}</td><td data-label="상태">${status(x.status)}</td></tr>`).join('')}
if(name==='payout'){const d=await req(API.payout);$('payoutType').value=d?.type||'INDIVIDUAL';$('accountHolder').value=d?.accountHolder||'';$('bankName').value=d?.bankName||'';$('accountNumber').value=d?.accountNumberMasked||'';$('settlementEmail').value=d?.settlementEmail||'';$('phone').value=d?.phone||'';$('businessName').value=d?.businessName||'';$('businessNumber').value=d?.businessNumberMasked||'';$('taxEmail').value=d?.taxEmail||'';business();$('savePayoutBtn').disabled=false}state.loaded.add(key)}catch(e){alert(e.code===401?'로그인 연결이 만료되었습니다.':'데이터를 불러오지 못했습니다.')}}
function currentPanel(){return document.querySelector('.nav-btn.active')?.dataset.panel||'overview'}
function activate(name){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id==='panel-'+name));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));load(name);scrollTo({top:0,behavior:'smooth'})}
async function changeScope(scope){if(!META[scope]||scope===state.scope)return;state.scope=scope;renderScopeText();alert('');const panel=currentPanel();try{const d=await dashboardFor(scope);renderDashboard(d);await load(panel)}catch{alert(`${META[scope].label} 데이터를 불러오지 못했습니다.`)}}
const consent=savedConsent();$('settlementConsent').checked=consent;$('partnerConsent').checked=consent;renderScopeText();syncRequestButton();
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>activate(b.dataset.panel));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>activate(b.dataset.go));document.querySelectorAll('.service-tab').forEach(b=>b.onclick=()=>changeScope(b.dataset.service));$('syncBtn').onclick=()=>{state.loaded.clear();Object.values(state.cache).forEach(x=>x.clear());initial(true);load(currentPanel(),true)};$('payoutType').onchange=business;$('settlementConsent').onchange=()=>{if($('settlementConsent').checked)rememberConsent('settlement-check');syncRequestButton()};$('partnerConsent').onchange=()=>{if($('partnerConsent').checked)rememberConsent('payout-check')};$('copyCodeBtn').onclick=async()=>{await navigator.clipboard.writeText(state.code);toast('추천인 코드를 복사했습니다.')};$('copyLinkBtn').onclick=async()=>{if(!state.inviteUrl)return toast('초대 링크가 없습니다.');await navigator.clipboard.writeText(state.inviteUrl);toast('초대 링크를 복사했습니다.')};$('shareBtn').onclick=async()=>{const m=META[state.scope];if(navigator.share)await navigator.share({title:`${m.label} 추천`,text:`추천인 코드: ${state.code}`,url:state.inviteUrl||location.origin});else{await navigator.clipboard.writeText(state.inviteUrl||state.code);toast('공유 내용을 복사했습니다.')}};$('requestBtn').onclick=async()=>{if(!$('settlementConsent').checked)return alert('파트너 약관과 정산정책 동의가 필요합니다.');await persistConsent('settlement-request');try{await req(API.request,{method:'POST',body:JSON.stringify({service:META[state.scope].api})});toast(`${META[state.scope].label} 지급 요청을 접수했습니다.`);state.cache.dashboard.clear();state.cache.settlements.clear();state.loaded.delete(`${state.scope}:settlements`);await initial(true);await load('settlements',true)}catch(e){alert('지급 요청을 처리하지 못했습니다.')}};$('payoutForm').onsubmit=async e=>{e.preventDefault();if(!$('partnerConsent').checked)return alert('파트너 약관과 개인정보 처리 안내 동의가 필요합니다.');const o=Object.fromEntries(new FormData(e.currentTarget).entries());delete o.partnerConsent;if(o.accountNumber&&o.accountNumber.includes('*'))delete o.accountNumber;await persistConsent('payout-save');try{await req(API.payout,{method:'PUT',body:JSON.stringify(o)});toast('정산 정보를 저장했습니다.')}catch(x){alert('정산 정보를 저장하지 못했습니다.')}};initial();
})();
